### ISSUE TITLE
It just won't run

### ISSUE THREAD

**Issue by TwarogSzatana** [Jacbo1/CE-Redef#1]
As in the title - all I see is cmd console for a fraction of a second and then nothing happens. Tried java and openJDK both

**Comment by Jacbo1** [comment]
v1.1 should work with JRE 8 but v1.2 requires JDK 17. I am just about done fixing the JDK 17 requirement.

**Comment by Jacbo1** [comment]
Alright so it seems that the GUI fix and performance increase in v1.2 are entirely because that was compiled with JDK 17. Compiling with JDK 8, which allows it to run with the standard JRE 8 from java.com which is what I think most people have installed is the same as v1.1. In short, v1.2 is going to be put on a different branch for JDK 17 users.

What version of Redef did you use and what JRE do you have installed? If you go to C:\Program Files\Java\ you can check. If it's Java 8 you'll have a folder called "jre1.8.0_301" there. If you do have that, try running the program through command prompt. Run `"C:\Program Files\Java\jre1.8.0_301\bin\java.exe" -jar "path to CE_Redef.jar"`. Either it will print an error or it will run normally. If it runs normally, then you should try using [Jarfix](https://johann.loefflmann.net/en/software/jarfix/index.html) to restore the file association including launch parameters. If Jarfix has no effect, you may need to uninstall the JDK if you have it and run Jarfix again.
